apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-jgroups
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.keycloak.app.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ .Values.keycloak.app.name }}
      ports:
        - protocol: TCP
          port: 7800