apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-db
  namespace: keycloak
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: keycloak
      ports:
        - protocol: TCP
          port: 5432

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-keycloak-egress
  namespace: keycloak
spec:
  podSelector:
    matchLabels:
      app: keycloak
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
      ports:
        - protocol: TCP
          port: 5432

    # dobbiamo permettere a keycloak di generare traffico in uscita anche verso le altre repliche
    - to:
        - podSelector:
            matchLabels:
              app: keycloak
      ports:
        - protocol: TCP
          port: 7800

    # Quando KC prova a connettersi al db mediante il suo service name "postgres-svc"
    # deve risolvere il nome via DNS e questo è fornito da Kubernetes mediante il suo CoreDNS che è nella kube-system.
    # Il CoreDNS è in ascolto sulla porta 53 UDP e TCP
    # Senza di questo blocco, keycloak non riesce a risolvere il nome "postgres-svc" e da errore di unknown-host
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53