apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kubelet-probes
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.keycloak.app.name }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 9000   # management port per health probes