apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.svc.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.keycloak.app.name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: jgroups
      port: 7800
      targetPort: 7800