apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-admin
  namespace: {{ .Values.global.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
#  annotations:
#    nginx.ingress.kubernetes.io/whitelist-source-range: "127.0.0.1/32,192.168.0.0/16"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.admin.host }}
      secretName: {{ .Values.ingress.admin.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.admin.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.svc.name }}
                port:
                  number: {{ .Values.keycloak.app.httpPort }}