apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-public
  namespace: {{ .Values.global.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "self-signed-cluster-issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.public.host }}
      secretName: {{ .Values.ingress.public.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.public.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.svc.name }}
                port:
                  number: {{ .Values.keycloak.app.httpPort }}