apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.svc.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.postgres.app.name }}
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}