apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.app.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.app.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.app.name }}
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.name }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: password
          ports:
            - containerPort: {{ .Values.postgres.port | int }}
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"