apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-admin-cert
  namespace: {{ .Values.global.namespace }}
spec:
  secretName: {{ .Values.ingress.admin.tls.secretName }}
  issuerRef:
    name: {{ .Values.global.tls.issuerRef }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.admin.host }}